[api_keys]
OPENAI_API_KEY="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"
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY = "ls__a7cd2f20a500436e8ee0e3fab36a43ea"
LANGCHAIN_PROJECT="Streamlit Demo"